{% set name = "qfit" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qfit-{{ version }}.tar.gz
  sha256: 64a70854820ba438e9361f4be8bc0b881e826b368c1ee3b5a8e40199c03ab00c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv 
  number: 0

requirements:
  host:
    - python 3.10
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10
    - numpy >=1.14.2
    - scipy >=1.1.0
    - matplotlib-base >=3.1.2
    - pyside6
    - h5py >=2.7.1
    - scikit-image
    - scqubits >=3.0.0
    - matplotlib-label-lines
    - ipykernel
    - jupyter
    - pathos
    - dill

test:
  requires:
    - pip
  imports:
    - qfit

about:
  home: https://github.com/scqubits/qfit
  summary: 'qfit: data extraction GUI tool for use with scQubits'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Harrinive
    - ZhaoTianPu
