# ui_window.py
#
# This file is part of datapyc.
#
#    Copyright (c) 2020, Jens Koch
#    All rights reserved.
#
#    This source code is licensed under the BSD-style license found in the
#    LICENSE file in the root directory of this source tree.
############################################################################

import os

from PySide2 import QtCore, QtGui, QtWidgets

from datapyc.views.calibration_view import CalibrationLineEdit
from datapyc.views.canvas_view import FigureCanvas
from datapyc.views.extractdata_view import TableView, ListView
from datapyc.ui.rangeslider import RangeSlider

import datapyc.ui.resources_rc


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 1024)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.dataTableView = TableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTableView.sizePolicy().hasHeightForWidth())
        self.dataTableView.setSizePolicy(sizePolicy)
        self.dataTableView.setMinimumSize(QtCore.QSize(0, 150))
        self.dataTableView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.dataTableView.setStyleSheet("")
        self.dataTableView.setObjectName("dataTableView")
        self.gridLayout.addWidget(self.dataTableView, 9, 4, 1, 1)

        self.gridGroupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox_3.sizePolicy().hasHeightForWidth())
        self.gridGroupBox_3.setSizePolicy(sizePolicy)
        self.gridGroupBox_3.setMinimumSize(QtCore.QSize(430, 0))
        self.gridGroupBox_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.gridGroupBox_3.setObjectName("gridGroupBox_3")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rawX1LineEdit = CalibrationLineEdit(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawX1LineEdit.sizePolicy().hasHeightForWidth())
        self.rawX1LineEdit.setSizePolicy(sizePolicy)
        self.rawX1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawX1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawX1LineEdit.setObjectName("rawX1LineEdit")
        self.gridLayout_2.addWidget(self.rawX1LineEdit, 0, 2, 1, 1)
        self.calibrateX2Button = QtWidgets.QToolButton(self.gridGroupBox_3)
        self.calibrateX2Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrateX2Button.setIcon(icon)
        self.calibrateX2Button.setObjectName("calibrateX2Button")
        self.gridLayout_2.addWidget(self.calibrateX2Button, 1, 0, 1, 1)
        self.mapX2LineEdit = CalibrationLineEdit(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapX2LineEdit.sizePolicy().hasHeightForWidth())
        self.mapX2LineEdit.setSizePolicy(sizePolicy)
        self.mapX2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapX2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapX2LineEdit.setObjectName("mapX2LineEdit")
        self.gridLayout_2.addWidget(self.mapX2LineEdit, 1, 4, 1, 1)
        self.rawX2LineEdit = CalibrationLineEdit(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawX2LineEdit.sizePolicy().hasHeightForWidth())
        self.rawX2LineEdit.setSizePolicy(sizePolicy)
        self.rawX2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawX2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawX2LineEdit.setObjectName("rawX2LineEdit")
        self.gridLayout_2.addWidget(self.rawX2LineEdit, 1, 2, 1, 1)
        self.mapX1LineEdit = CalibrationLineEdit(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapX1LineEdit.sizePolicy().hasHeightForWidth())
        self.mapX1LineEdit.setSizePolicy(sizePolicy)
        self.mapX1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapX1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapX1LineEdit.setInputMask("")
        self.mapX1LineEdit.setObjectName("mapX1LineEdit")
        self.gridLayout_2.addWidget(self.mapX1LineEdit, 0, 4, 1, 1)
        self.calibrateX1Button = QtWidgets.QToolButton(self.gridGroupBox_3)
        self.calibrateX1Button.setText("")
        self.calibrateX1Button.setIcon(icon)
        self.calibrateX1Button.setObjectName("calibrateX1Button")
        self.gridLayout_2.addWidget(self.calibrateX1Button, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridGroupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox_3, 5, 1, 1, 2)
        self.gridGroupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox_4.sizePolicy().hasHeightForWidth())
        self.gridGroupBox_4.setSizePolicy(sizePolicy)
        self.gridGroupBox_4.setMinimumSize(QtCore.QSize(430, 0))
        self.gridGroupBox_4.setMaximumSize(QtCore.QSize(500, 16777215))
        self.gridGroupBox_4.setObjectName("gridGroupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridGroupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.rawY2LineEdit = CalibrationLineEdit(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawY2LineEdit.sizePolicy().hasHeightForWidth())
        self.rawY2LineEdit.setSizePolicy(sizePolicy)
        self.rawY2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawY2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawY2LineEdit.setObjectName("rawY2LineEdit")
        self.gridLayout_7.addWidget(self.rawY2LineEdit, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 1, 1, 1)
        self.calibrateY2Button = QtWidgets.QToolButton(self.gridGroupBox_4)
        self.calibrateY2Button.setText("")
        self.calibrateY2Button.setIcon(icon)
        self.calibrateY2Button.setObjectName("calibrateY2Button")
        self.gridLayout_7.addWidget(self.calibrateY2Button, 1, 0, 1, 1)
        self.calibrateY1Button = QtWidgets.QToolButton(self.gridGroupBox_4)
        self.calibrateY1Button.setText("")
        self.calibrateY1Button.setIcon(icon)
        self.calibrateY1Button.setObjectName("calibrateY1Button")
        self.gridLayout_7.addWidget(self.calibrateY1Button, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 1, 1, 1)
        self.mapY1LineEdit = CalibrationLineEdit(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapY1LineEdit.sizePolicy().hasHeightForWidth())
        self.mapY1LineEdit.setSizePolicy(sizePolicy)
        self.mapY1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapY1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapY1LineEdit.setObjectName("mapY1LineEdit")
        self.gridLayout_7.addWidget(self.mapY1LineEdit, 0, 4, 1, 1)
        self.mapY2LineEdit = CalibrationLineEdit(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapY2LineEdit.sizePolicy().hasHeightForWidth())
        self.mapY2LineEdit.setSizePolicy(sizePolicy)
        self.mapY2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapY2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapY2LineEdit.setObjectName("mapY2LineEdit")
        self.gridLayout_7.addWidget(self.mapY2LineEdit, 1, 4, 1, 1)
        self.rawY1LineEdit = CalibrationLineEdit(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawY1LineEdit.sizePolicy().hasHeightForWidth())
        self.rawY1LineEdit.setSizePolicy(sizePolicy)
        self.rawY1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawY1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawY1LineEdit.setObjectName("rawY1LineEdit")
        self.gridLayout_7.addWidget(self.rawY1LineEdit, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox_4, 6, 1, 1, 2)

        self.mplFigureCanvas = FigureCanvas(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplFigureCanvas.sizePolicy().hasHeightForWidth())
        self.mplFigureCanvas.setSizePolicy(sizePolicy)
        self.mplFigureCanvas.setMinimumSize(QtCore.QSize(0, 60))
        self.mplFigureCanvas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mplFigureCanvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mplFigureCanvas.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mplFigureCanvas.setLineWidth(2)
        self.mplFigureCanvas.setObjectName("mplFigureCanvas")

        self.resetViewButton = QtWidgets.QPushButton(self.mplFigureCanvas)
        self.resetViewButton.setGeometry(QtCore.QRect(10, 20, 40, 40))
        self.resetViewButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetViewButton.setIcon(icon8)
        self.resetViewButton.setObjectName("resetViewButton")
        self.panViewButton = QtWidgets.QPushButton(self.mplFigureCanvas)
        self.panViewButton.setGeometry(QtCore.QRect(60, 20, 40, 40))
        self.panViewButton.setCursor(QtCore.Qt.ArrowCursor)
        self.panViewButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panViewButton.setIcon(icon9)
        self.panViewButton.setCheckable(True)
        self.panViewButton.setAutoExclusive(True)
        self.panViewButton.setObjectName("panViewButton")
        self.zoomViewButton = QtWidgets.QPushButton(self.mplFigureCanvas)
        self.zoomViewButton.setGeometry(QtCore.QRect(110, 20, 40, 40))
        self.zoomViewButton.setCursor(QtCore.Qt.ArrowCursor)
        self.zoomViewButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomViewButton.setIcon(icon10)
        self.zoomViewButton.setCheckable(True)
        self.zoomViewButton.setAutoExclusive(True)
        self.zoomViewButton.setObjectName("zoomViewButton")
        self.selectViewButton = QtWidgets.QPushButton(self.mplFigureCanvas)
        self.selectViewButton.setGeometry(QtCore.QRect(160, 20, 41, 41))
        self.selectViewButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/selectmode.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.selectViewButton.setIcon(icon11)
        self.selectViewButton.setCheckable(True)
        self.selectViewButton.setChecked(True)
        self.selectViewButton.setAutoExclusive(True)
        self.selectViewButton.setObjectName("selectViewButton")
        self.swapXYButton = QtWidgets.QPushButton(self.mplFigureCanvas)
        self.swapXYButton.setGeometry(QtCore.QRect(210, 20, 71, 41))
        self.swapXYButton.setObjectName("swapXYButton")
        self.gridLayout.addWidget(self.mplFigureCanvas, 0, 4, 9, 1)

        self.gridGroupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox_2.sizePolicy().hasHeightForWidth())
        self.gridGroupBox_2.setSizePolicy(sizePolicy)
        self.gridGroupBox_2.setMinimumSize(QtCore.QSize(330, 0))
        self.gridGroupBox_2.setMaximumSize(QtCore.QSize(500, 200))
        self.gridGroupBox_2.setObjectName("gridGroupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridGroupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.yComboBox = QtWidgets.QComboBox(self.gridGroupBox_2)
        self.yComboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.yComboBox.setObjectName("yComboBox")
        self.gridLayout_3.addWidget(self.yComboBox, 4, 1, 1, 1)
        self.zComboBox = QtWidgets.QComboBox(self.gridGroupBox_2)
        self.zComboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.zComboBox.setObjectName("zComboBox")
        self.gridLayout_3.addWidget(self.zComboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridGroupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.xComboBox = QtWidgets.QComboBox(self.gridGroupBox_2)
        self.xComboBox.setMinimumSize(QtCore.QSize(250, 0))
        self.xComboBox.setObjectName("xComboBox")
        self.gridLayout_3.addWidget(self.xComboBox, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridGroupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridGroupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.gridGroupBox_2, 3, 1, 1, 2)

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        # self.groupBox_2.setMinimumSize(QtCore.QSize(80, 100))
        # self.groupBox_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newRowButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newRowButton.sizePolicy().hasHeightForWidth())
        self.newRowButton.setSizePolicy(sizePolicy)
        self.newRowButton.setObjectName("newRowButton")
        self.verticalLayout.addWidget(self.newRowButton)
        self.deleteRowButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteRowButton.sizePolicy().hasHeightForWidth())
        self.deleteRowButton.setSizePolicy(sizePolicy)
        self.deleteRowButton.setObjectName("deleteRowButton")
        self.verticalLayout.addWidget(self.deleteRowButton)
        self.clearAllButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearAllButton.sizePolicy().hasHeightForWidth())
        self.clearAllButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearAllButton.setIcon(icon1)
        self.clearAllButton.setObjectName("clearAllButton")
        self.verticalLayout.addWidget(self.clearAllButton)
        self.gridLayout.addWidget(self.groupBox_2, 9, 1, 1, 1)

        self.datasetListView = ListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetListView.sizePolicy().hasHeightForWidth())
        self.datasetListView.setSizePolicy(sizePolicy)
        self.datasetListView.setMinimumSize(QtCore.QSize(0, 150))
        self.datasetListView.setMaximumSize(QtCore.QSize(230, 150))
        self.datasetListView.setObjectName("datasetListView")
        self.gridLayout.addWidget(self.datasetListView, 9, 2, 1, 1)

        self.verticalGroupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox_3.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox_3.setSizePolicy(sizePolicy)
        self.verticalGroupBox_3.setMinimumSize(QtCore.QSize(430, 0))
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.verticalGroupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.bgndSubtractXCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.bgndSubtractXCheckBox.setChecked(False)
        self.bgndSubtractXCheckBox.setTristate(False)
        self.bgndSubtractXCheckBox.setObjectName("bgndSubtractXCheckBox")
        self.gridLayout_6.addWidget(self.bgndSubtractXCheckBox, 2, 0, 1, 1)
        self.bgndSubtractYCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.bgndSubtractYCheckBox.setObjectName("bgndSubtractYCheckBox")
        self.gridLayout_6.addWidget(self.bgndSubtractYCheckBox, 2, 1, 1, 1)
        self.savgolFilterYCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.savgolFilterYCheckBox.setObjectName("savgolFilterYCheckBox")
        self.gridLayout_6.addWidget(self.savgolFilterYCheckBox, 0, 1, 1, 1)
        self.savgolFilterXCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.savgolFilterXCheckBox.setObjectName("savgolFilterXCheckBox")
        self.gridLayout_6.addWidget(self.savgolFilterXCheckBox, 0, 0, 1, 1)
        self.gaussLaplaceCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.gaussLaplaceCheckBox.setObjectName("gaussLaplaceCheckBox")
        self.gridLayout_6.addWidget(self.gaussLaplaceCheckBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.verticalGroupBox_3, 0, 1, 1, 2)

        self.calibratedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibratedCheckBox.sizePolicy().hasHeightForWidth())
        self.calibratedCheckBox.setSizePolicy(sizePolicy)
        self.calibratedCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.calibratedCheckBox.setObjectName("calibratedCheckBox")
        self.gridLayout.addWidget(self.calibratedCheckBox, 8, 2, 1, 1)

        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setMinimumSize(QtCore.QSize(430, 0))
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")

        self.colorComboBox = QtWidgets.QComboBox(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorComboBox.sizePolicy().hasHeightForWidth())
        self.colorComboBox.setSizePolicy(sizePolicy)
        self.colorComboBox.setIconSize(QtCore.QSize(150, 10))
        self.colorComboBox.setObjectName("colorComboBox")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/PuOr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/RdYlBu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/bwr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/viridis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/cividis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon9, "")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon10, "")
        self.gridLayout_5.addWidget(self.colorComboBox, 0, 0, 1, 1)

        self.logScaleCheckBox = QtWidgets.QCheckBox(self.gridGroupBox)
        self.logScaleCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.logScaleCheckBox.setObjectName("logScaleCheckBox")
        self.gridLayout_5.addWidget(self.logScaleCheckBox, 0, 1, 1, 1)

        self.rangeSliderWidget = RangeSlider(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangeSliderWidget.sizePolicy().hasHeightForWidth())
        self.rangeSliderWidget.setSizePolicy(sizePolicy)
        self.rangeSliderWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.rangeSliderWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.rangeSliderWidget.setObjectName("rangeSliderWidget")
        self.gridLayout_5.addWidget(self.rangeSliderWidget, 1, 0, 1, 2)

        self.gridLayout.addWidget(self.gridGroupBox, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 2)

        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 4, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "datapyc", None, -1))
        self.gridGroupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Calibrate X Axis", None, -1))
        self.rawX1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.calibrateX2Button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Calibrate x2, allows selection of coordinate inside plot", None, -1))
        self.mapX2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.rawX2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.mapX1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.calibrateX1Button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Calibrate x1, allows selection of coordinate inside plot", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">X<span style=\" vertical-align:sub;\">1</span></p></body></html>", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">X<span style=\" vertical-align:sub;\">2</span></p></body></html>", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">→ X<span style=\" vertical-align:sub;\">1</span>\'</p></body></html>", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">→ X<span style=\" vertical-align:sub;\">2</span>\'</p></body></html>", None, -1))
        self.gridGroupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Calibrate Y Axis", None, -1))
        self.rawY2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">Y<span style=\" vertical-align:sub;\">1</span></p></body></html>", None, -1))
        self.calibrateY2Button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Calibrate y2, allows selection of coordinate inside plot", None, -1))
        self.calibrateY1Button.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Calibrate y1, allows selection of coordinate inside plot", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">Y<span style=\" vertical-align:sub;\">2</span></p></body></html>", None, -1))
        self.mapY1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.mapY2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.rawY1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">→ Y<span style=\" vertical-align:sub;\">1</span>\'</p></body></html>", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p align=\"right\">→ Y<span style=\" vertical-align:sub;\">2</span>\'</p></body></html>", None, -1))
        self.resetViewButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reset plot area", None, -1))
        self.panViewButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Pan mode: move plot region by dragging", None, -1))
        self.zoomViewButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Zoom mode: select a plot region to enlarge", None, -1))
        self.swapXYButton.setText(QtWidgets.QApplication.translate("MainWindow", "X↔Y", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Z Values", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Axis-2 Values", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Axis-1 Values", None, -1))
        self.newRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "New dataset", None, -1))
        self.deleteRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete dataset", None, -1))
        self.clearAllButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear all", None, -1))
        self.verticalGroupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Image Options", None, -1))
        self.bgndSubtractXCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Background subtraction along X", None, -1))
        self.bgndSubtractXCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Subtract Bgnd X", None, -1))
        self.bgndSubtractYCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Background subtraction along Y", None, -1))
        self.bgndSubtractYCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Subtract Bgnd Y", None, -1))
        self.savgolFilterYCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Savitzky-Golay filter (Y cuts)", None, -1))
        self.savgolFilterYCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Sav-Gol Filter Y", None, -1))
        self.gaussLaplaceCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Apply Gauss-Laplace filter", None, -1))
        self.gaussLaplaceCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Gauss-Laplace", None, -1))
        self.savgolFilterXCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Savitzky-Golay filter (X cuts)", None, -1))
        self.savgolFilterXCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Sav-Gol Filter X", None, -1))
        self.calibratedCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Apply calibration", None, -1))
        self.gridGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Color Options", None, -1))
        self.colorComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "PuOr", None, -1))
        self.colorComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "RdYlBu", None, -1))
        self.colorComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "bwr", None, -1))
        self.colorComboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "viridis", None, -1))
        self.colorComboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "cividis", None, -1))
        self.colorComboBox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "gray", None, -1))
        self.logScaleCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Log Colorscale", None, -1))
        self.rangeSliderWidget.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adjust plot range (Z)", None, -1))
        self.rangeSliderWidget.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Color Range", None, -1))
