# ui_mainwindow.py
#
# This file is part of datapyc.
#
#    Copyright (c) 2020, Jens Koch
#    All rights reserved.
#
#    This source code is licensed under the BSD-style license found in the
#    LICENSE file in the root directory of this source tree.
############################################################################


import os

from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtQuickWidgets import QQuickWidget

from datapyc.core.calibrationview import CalibrationLineEdit
from datapyc.core.canvasview import FigureCanvas
from datapyc.core.dataview import TableView, ListView
import datapyc.core.resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 1024)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.resetViewButton = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.resetViewButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetViewButton.setIcon(icon1)
        self.resetViewButton.setObjectName("resetViewButton")
        self.horizontalLayout.addWidget(self.resetViewButton)
        self.panViewButton = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.panViewButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/move.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.panViewButton.setIcon(icon2)
        self.panViewButton.setCheckable(False)
        self.panViewButton.setObjectName("panViewButton")
        self.horizontalLayout.addWidget(self.panViewButton)
        self.zoomViewButton = QtWidgets.QPushButton(self.horizontalGroupBox)
        self.zoomViewButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomViewButton.setIcon(icon3)
        self.zoomViewButton.setCheckable(False)
        self.zoomViewButton.setObjectName("zoomViewButton")
        self.horizontalLayout.addWidget(self.zoomViewButton)
        self.verticalLayout_4.addWidget(self.horizontalGroupBox)
        self.verticalGroupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.verticalGroupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.bgndSubtractXCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.bgndSubtractXCheckBox.setChecked(False)
        self.bgndSubtractXCheckBox.setTristate(False)
        self.bgndSubtractXCheckBox.setObjectName("bgndSubtractXCheckBox")
        self.gridLayout_6.addWidget(self.bgndSubtractXCheckBox, 2, 0, 1, 1)
        self.bgndSubtractYCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.bgndSubtractYCheckBox.setObjectName("bgndSubtractYCheckBox")
        self.gridLayout_6.addWidget(self.bgndSubtractYCheckBox, 2, 1, 1, 1)
        self.swapXYCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.swapXYCheckBox.setFont(font)
        self.swapXYCheckBox.setObjectName("swapXYCheckBox")
        self.gridLayout_6.addWidget(self.swapXYCheckBox, 2, 2, 1, 1)
        self.savgolFilterXCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.savgolFilterXCheckBox.setObjectName("savgolFilterXCheckBox")
        self.gridLayout_6.addWidget(self.savgolFilterXCheckBox, 0, 0, 1, 1)
        self.savgolFilterYCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.savgolFilterYCheckBox.setObjectName("savgolFilterYCheckBox")
        self.gridLayout_6.addWidget(self.savgolFilterYCheckBox, 0, 1, 1, 1)
        self.gaussLaplaceCheckBox = QtWidgets.QCheckBox(self.verticalGroupBox_3)
        self.gaussLaplaceCheckBox.setObjectName("gaussLaplaceCheckBox")
        self.gridLayout_6.addWidget(self.gaussLaplaceCheckBox, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.verticalGroupBox_3)
        self.gridGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.colorComboBox = QtWidgets.QComboBox(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorComboBox.sizePolicy().hasHeightForWidth())
        self.colorComboBox.setSizePolicy(sizePolicy)
        self.colorComboBox.setIconSize(QtCore.QSize(100, 10))
        self.colorComboBox.setObjectName("colorComboBox")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/PuOr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/RdYlBu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/bwr.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/viridis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon7, "")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/cividis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon8, "")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/gray.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorComboBox.addItem(icon9, "")
        self.gridLayout_4.addWidget(self.colorComboBox, 0, 0, 1, 1)
        self.logScaleCheckBox = QtWidgets.QCheckBox(self.gridGroupBox)
        self.logScaleCheckBox.setObjectName("logScaleCheckBox")
        self.gridLayout_4.addWidget(self.logScaleCheckBox, 0, 1, 1, 1)
        self.quickWidget = QQuickWidget(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quickWidget.sizePolicy().hasHeightForWidth())
        self.quickWidget.setSizePolicy(sizePolicy)
        self.quickWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.quickWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.quickWidget.setAutoFillBackground(True)
        self.quickWidget.setResizeMode(QQuickWidget.SizeRootObjectToView)
        qml_file = os.path.join(os.path.dirname(__file__), "rangeslider.qml")
        self.quickWidget.setSource(QtCore.QUrl.fromLocalFile(os.path.abspath(qml_file)))
        self.quickWidget.setObjectName("quickWidget")
        self.gridLayout_4.addWidget(self.quickWidget, 1, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.gridGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridGroupBox1 = QtWidgets.QGroupBox(self.layoutWidget)
        self.gridGroupBox1.setObjectName("gridGroupBox1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridGroupBox1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.zComboBox = QtWidgets.QComboBox(self.gridGroupBox1)
        self.zComboBox.setObjectName("zComboBox")
        self.gridLayout_3.addWidget(self.zComboBox, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridGroupBox1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.xComboBox = QtWidgets.QComboBox(self.gridGroupBox1)
        self.xComboBox.setObjectName("xComboBox")
        self.gridLayout_3.addWidget(self.xComboBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridGroupBox1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.yComboBox = QtWidgets.QComboBox(self.gridGroupBox1)
        self.yComboBox.setObjectName("yComboBox")
        self.gridLayout_3.addWidget(self.yComboBox, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridGroupBox1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.gridGroupBox1)
        self.gridGroupBox2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.gridGroupBox2.setObjectName("gridGroupBox2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox2)
        self.gridLayout.setObjectName("gridLayout")
        self.rawX1LineEdit = CalibrationLineEdit(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawX1LineEdit.sizePolicy().hasHeightForWidth())
        self.rawX1LineEdit.setSizePolicy(sizePolicy)
        self.rawX1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawX1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawX1LineEdit.setObjectName("rawX1LineEdit")
        self.gridLayout.addWidget(self.rawX1LineEdit, 0, 2, 1, 1)
        self.calibrateX2Button = QtWidgets.QToolButton(self.gridGroupBox2)
        self.calibrateX2Button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrateX2Button.setIcon(icon10)
        self.calibrateX2Button.setObjectName("calibrateX2Button")
        self.gridLayout.addWidget(self.calibrateX2Button, 1, 0, 1, 1)
        self.mapX2LineEdit = CalibrationLineEdit(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapX2LineEdit.sizePolicy().hasHeightForWidth())
        self.mapX2LineEdit.setSizePolicy(sizePolicy)
        self.mapX2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapX2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapX2LineEdit.setObjectName("mapX2LineEdit")
        self.gridLayout.addWidget(self.mapX2LineEdit, 1, 4, 1, 1)
        self.rawX2LineEdit = CalibrationLineEdit(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawX2LineEdit.sizePolicy().hasHeightForWidth())
        self.rawX2LineEdit.setSizePolicy(sizePolicy)
        self.rawX2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawX2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawX2LineEdit.setObjectName("rawX2LineEdit")
        self.gridLayout.addWidget(self.rawX2LineEdit, 1, 2, 1, 1)
        self.mapX1LineEdit = CalibrationLineEdit(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapX1LineEdit.sizePolicy().hasHeightForWidth())
        self.mapX1LineEdit.setSizePolicy(sizePolicy)
        self.mapX1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapX1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapX1LineEdit.setInputMask("")
        self.mapX1LineEdit.setObjectName("mapX1LineEdit")
        self.gridLayout.addWidget(self.mapX1LineEdit, 0, 4, 1, 1)
        self.calibrateX1Button = QtWidgets.QToolButton(self.gridGroupBox2)
        self.calibrateX1Button.setText("")
        self.calibrateX1Button.setIcon(icon10)
        self.calibrateX1Button.setObjectName("calibrateX1Button")
        self.gridLayout.addWidget(self.calibrateX1Button, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridGroupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.gridGroupBox2)
        self.gridGroupBox3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.gridGroupBox3.setObjectName("gridGroupBox3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridGroupBox3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rawY2LineEdit = CalibrationLineEdit(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawY2LineEdit.sizePolicy().hasHeightForWidth())
        self.rawY2LineEdit.setSizePolicy(sizePolicy)
        self.rawY2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawY2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawY2LineEdit.setObjectName("rawY2LineEdit")
        self.gridLayout_2.addWidget(self.rawY2LineEdit, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 1, 1, 1)
        self.calibrateY2Button = QtWidgets.QToolButton(self.gridGroupBox3)
        self.calibrateY2Button.setText("")
        self.calibrateY2Button.setIcon(icon10)
        self.calibrateY2Button.setObjectName("calibrateY2Button")
        self.gridLayout_2.addWidget(self.calibrateY2Button, 1, 0, 1, 1)
        self.calibrateY1Button = QtWidgets.QToolButton(self.gridGroupBox3)
        self.calibrateY1Button.setText("")
        self.calibrateY1Button.setIcon(icon10)
        self.calibrateY1Button.setObjectName("calibrateY1Button")
        self.gridLayout_2.addWidget(self.calibrateY1Button, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 1, 1, 1)
        self.mapY1LineEdit = CalibrationLineEdit(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapY1LineEdit.sizePolicy().hasHeightForWidth())
        self.mapY1LineEdit.setSizePolicy(sizePolicy)
        self.mapY1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapY1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapY1LineEdit.setObjectName("mapY1LineEdit")
        self.gridLayout_2.addWidget(self.mapY1LineEdit, 0, 4, 1, 1)
        self.mapY2LineEdit = CalibrationLineEdit(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapY2LineEdit.sizePolicy().hasHeightForWidth())
        self.mapY2LineEdit.setSizePolicy(sizePolicy)
        self.mapY2LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.mapY2LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mapY2LineEdit.setObjectName("mapY2LineEdit")
        self.gridLayout_2.addWidget(self.mapY2LineEdit, 1, 4, 1, 1)
        self.rawY1LineEdit = CalibrationLineEdit(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rawY1LineEdit.sizePolicy().hasHeightForWidth())
        self.rawY1LineEdit.setSizePolicy(sizePolicy)
        self.rawY1LineEdit.setMinimumSize(QtCore.QSize(80, 0))
        self.rawY1LineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.rawY1LineEdit.setObjectName("rawY1LineEdit")
        self.gridLayout_2.addWidget(self.rawY1LineEdit, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridGroupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.gridGroupBox3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.calibratedCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.calibratedCheckBox.setObjectName("calibratedCheckBox")
        self.gridLayout_7.addWidget(self.calibratedCheckBox, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4.addLayout(self.gridLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.mplFigureCanvas = FigureCanvas(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplFigureCanvas.sizePolicy().hasHeightForWidth())
        self.mplFigureCanvas.setSizePolicy(sizePolicy)
        self.mplFigureCanvas.setMinimumSize(QtCore.QSize(0, 60))
        self.mplFigureCanvas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mplFigureCanvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mplFigureCanvas.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mplFigureCanvas.setLineWidth(2)
        self.mplFigureCanvas.setObjectName("mplFigureCanvas")
        self.horizontalLayout_4.addWidget(self.mplFigureCanvas)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalGroupBox1 = QtWidgets.QGroupBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox1.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox1.setSizePolicy(sizePolicy)
        self.horizontalGroupBox1.setMinimumSize(QtCore.QSize(0, 140))
        self.horizontalGroupBox1.setMaximumSize(QtCore.QSize(16777215, 160))
        self.horizontalGroupBox1.setObjectName("horizontalGroupBox1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.newRowButton = QtWidgets.QPushButton(self.horizontalGroupBox1)
        self.newRowButton.setObjectName("newRowButton")
        self.verticalLayout_5.addWidget(self.newRowButton)
        self.deleteRowButton = QtWidgets.QPushButton(self.horizontalGroupBox1)
        self.deleteRowButton.setObjectName("deleteRowButton")
        self.verticalLayout_5.addWidget(self.deleteRowButton)
        self.clearAllButton = QtWidgets.QPushButton(self.horizontalGroupBox1)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearAllButton.setIcon(icon11)
        self.clearAllButton.setObjectName("clearAllButton")
        self.verticalLayout_5.addWidget(self.clearAllButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.datasetListView = ListView(self.horizontalGroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetListView.sizePolicy().hasHeightForWidth())
        self.datasetListView.setSizePolicy(sizePolicy)
        self.datasetListView.setMinimumSize(QtCore.QSize(0, 140))
        self.datasetListView.setMaximumSize(QtCore.QSize(150, 150))
        self.datasetListView.setObjectName("datasetListView")
        self.horizontalLayout_5.addWidget(self.datasetListView)
        self.dataTableView = TableView(self.horizontalGroupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTableView.sizePolicy().hasHeightForWidth())
        self.dataTableView.setSizePolicy(sizePolicy)
        self.dataTableView.setMinimumSize(QtCore.QSize(0, 140))
        self.dataTableView.setMaximumSize(QtCore.QSize(16777215, 140))
        self.dataTableView.setStyleSheet("")
        self.dataTableView.setObjectName("dataTableView")
        self.horizontalLayout_5.addWidget(self.dataTableView)
        self.horizontalLayout_3.addWidget(self.horizontalGroupBox1)
        self.verticalLayout.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "datapyc", None, -1))
        self.resetViewButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Reset plot area", None, -1))
        self.panViewButton.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Pan mode: move plot region by dragging", None, -1))
        self.zoomViewButton.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Zoom mode: select a plot region to enlarge", None, -1))
        self.verticalGroupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Image Options", None, -1))
        self.bgndSubtractXCheckBox.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Background subtraction along X", None, -1))
        self.bgndSubtractXCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Subtract Bgnd X", None, -1))
        self.bgndSubtractYCheckBox.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Background subtraction along Y", None, -1))
        self.bgndSubtractYCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Subtract Bgnd Y", None, -1))
        self.swapXYCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Swap X and Y axes", None, -1))
        self.swapXYCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Swap X↔Y", None, -1))
        self.savgolFilterXCheckBox.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Savitzky-Golay filter (X cuts)", None, -1))
        self.savgolFilterXCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Sav-Gol Filter X", None, -1))
        self.savgolFilterYCheckBox.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Savitzky-Golay filter (Y cuts)", None, -1))
        self.savgolFilterYCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Sav-Gol Filter Y", None, -1))
        self.gaussLaplaceCheckBox.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Apply Gauss-Laplace filter", None, -1))
        self.gaussLaplaceCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Gauss-Laplace", None, -1))
        self.gridGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Color Options", None, -1))
        self.colorComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "PuOr", None, -1))
        self.colorComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "RdYlBu", None, -1))
        self.colorComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "bwr", None, -1))
        self.colorComboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "viridis", None, -1))
        self.colorComboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "cividis", None, -1))
        self.colorComboBox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "gray", None, -1))
        self.logScaleCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "Log Colorscale", None, -1))
        self.quickWidget.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adjust plot range (Z)", None, -1))
        self.quickWidget.setWhatsThis(QtWidgets.QApplication.translate("MainWindow", "Color Range", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Z Values", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Axis-1 Values", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Axis-2 Values", None, -1))
        self.gridGroupBox2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Calibrate X Axis", None, -1))
        self.rawX1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.calibrateX2Button.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Calibrate x2, allows selection of coordinate inside plot",
                                             None, -1))
        self.mapX2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.rawX2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.mapX1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.calibrateX1Button.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Calibrate x1, allows selection of coordinate inside plot",
                                             None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow",
                                                              "<html><head/><body><p align=\"right\">X<span style=\" vertical-align:sub;\">1</span></p></body></html>",
                                                              None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow",
                                                              "<html><head/><body><p align=\"right\">X<span style=\" vertical-align:sub;\">2</span></p></body></html>",
                                                              None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow",
                                                              "<html><head/><body><p align=\"right\">→ X<span style=\" vertical-align:sub;\">1</span>\'</p></body></html>",
                                                              None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow",
                                                              "<html><head/><body><p align=\"right\">→ X<span style=\" vertical-align:sub;\">2</span>\'</p></body></html>",
                                                              None, -1))
        self.gridGroupBox3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Calibrate Y Axis", None, -1))
        self.rawY2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow",
                                                              "<html><head/><body><p align=\"right\">Y<span style=\" vertical-align:sub;\">1</span></p></body></html>",
                                                              None, -1))
        self.calibrateY2Button.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Calibrate y2, allows selection of coordinate inside plot",
                                             None, -1))
        self.calibrateY1Button.setToolTip(
            QtWidgets.QApplication.translate("MainWindow", "Calibrate y1, allows selection of coordinate inside plot",
                                             None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow",
                                                              "<html><head/><body><p align=\"right\">Y<span style=\" vertical-align:sub;\">2</span></p></body></html>",
                                                              None, -1))
        self.mapY1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.mapY2LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "1.0", None, -1))
        self.rawY1LineEdit.setText(QtWidgets.QApplication.translate("MainWindow", "0.0", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow",
                                                               "<html><head/><body><p align=\"right\">→ Y<span style=\" vertical-align:sub;\">1</span>\'</p></body></html>",
                                                               None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow",
                                                               "<html><head/><body><p align=\"right\">→ Y<span style=\" vertical-align:sub;\">2</span>\'</p></body></html>",
                                                               None, -1))
        self.groupBox.setTitle(
            QtWidgets.QApplication.translate("MainWindow", "Apply calibration to data table below", None, -1))
        self.calibratedCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", " Show Calibrated", None, -1))
        self.newRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "New dataset", None, -1))
        self.deleteRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "Delete dataset", None, -1))
        self.clearAllButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear all", None, -1))
