name: Update meta.yaml on new tag

on:
  push:

jobs:
  update-meta:
    name: >-
      Update meta.yaml
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests 

      - name: Run meta.yaml updater
        run: python .github/workflows/update_meta_yaml.py

      - name: Commit changes
        run: |
          git config --global user.name "meta-yaml-updater[bot]"
          git config --global user.email "meta-yaml-updater[bot]@users.noreply.github.com"
          git checkout -b update-meta-${{ github.run_id }}
          git add meta.yaml
          git commit -m "Update meta.yaml for version update to ${GITHUB_REF}"
          git push --set-upstream origin update-meta-${{ github.run_id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update meta.yaml for new version"
          branch: update-meta-${{ github.run_id }}
          base: master
          title: "Update meta.yaml for new version"
          body: "This PR was automatically generated by the update workflow."
